# This is a sample Jupyter Notebook

Below is an example of a code cell. 
Put your cursor into the cell and press Shift+Enter to execute it and select the next one, or click 'Run Cell' button.

Press Double Shift to search everywhere for classes, files, tool windows, actions, and settings.

To learn more about Jupyter Notebooks in PyCharm, see [help](https://www.jetbrains.com/help/pycharm/ipython-notebook-support.html).
For an overview of PyCharm, go to Help -> Learn IDE features or refer to [our documentation](https://www.jetbrains.com/help/pycharm/getting-started.html).

In [249]:
url='https://companiesmarketcap.com/tesla/revenue/'

In [250]:
import requests
from bs4 import BeautifulSoup
import pandas as pd

In [251]:
html = requests.get(url).text

soup = BeautifulSoup(html, "html.parser")

In [252]:
table=soup.find_all('table')

In [253]:
table = soup.find("table")

In [254]:
data = []

In [255]:
for row in table.find_all('tr'):
    cells = row.find_all("td")

    if len(cells) >= 2:

            year = cells[0].text.strip()
            revenuee = cells[1].text.strip()
            data.append([year, revenuee])

In [256]:
revenue = pd.DataFrame(data, columns=["Year", "Revenue"])

In [257]:
print(revenue)

          Year   Revenue
0   2026 (TTM)  $97.87 B
1         2025  $94.82 B
2         2024  $97.69 B
3         2023  $96.77 B
4         2022  $81.46 B
5         2021  $53.82 B
6         2020  $31.53 B
7         2019  $24.57 B
8         2018  $21.46 B
9         2017  $11.75 B
10        2016   $7.00 B
11        2015   $4.04 B
12        2014   $3.19 B
13        2013   $2.01 B
14        2012   $0.41 B
15        2011   $0.20 B
16        2010   $0.11 B
17        2009   $0.11 B

In [258]:
revenue["Revenue"] = revenue["Revenue"].str.replace(",", "")
revenue["Revenue"] = revenue["Revenue"].str.replace("$", "", regex=False)
revenue["Year"] = revenue["Year"].str.replace(r"\s*\(.*?\)", "", regex=True)

revenue = revenue[revenue["Revenue"] != ""]

In [259]:
print(revenue.head())

   Year  Revenue
0  2026  97.87 B
1  2025  94.82 B
2  2024  97.69 B
3  2023  96.77 B
4  2022  81.46 B

In [260]:
url2='https://companiesmarketcap.com/nzd/amazon/revenue/'

In [261]:
html=requests.get(url2).text

In [262]:
soup=BeautifulSoup(html, "html.parser")

In [263]:
table=soup.find('table')

In [264]:
data2=[]

In [265]:
for row in table.find_all('tr'):
    cells = row.find_all("td")
    if len(cells) >= 2:
        year = cells[0].text.strip()
        revenuee = cells[1].text.strip()
        data2.append([year, revenuee])

In [266]:
revenue2=pd.DataFrame(data2, columns=["Year", "Revenue"])

In [267]:
print(revenue2.head())

         Year      Revenue
0  2026 (TTM)   NZ$1.269 T
1        2025   NZ$1.237 T
2        2024   NZ$1.131 T
3        2023  NZ$908.89 B
4        2022  NZ$809.54 B

In [268]:
revenue2["Year"] = revenue2["Year"].str.replace(r"\s*\(.*?\)", "", regex=True)
revenue2["Revenue"] = revenue2["Revenue"].str.replace("NZ$", "", regex=False)
revenue2["Revenue"] = revenue2["Revenue"].str.strip()

In [269]:

print(revenue2.head())

   Year   Revenue
0  2026   1.269 T
1  2025   1.237 T
2  2024   1.131 T
3  2023  908.89 B
4  2022  809.54 B

In [270]:
import yfinance as yf

In [271]:
tesla = yf.Ticker("TSLA")
tesla_data = tesla.history(period="max")
tesla_data.reset_index(inplace=True)

In [272]:
print(tesla_data.head())

                       Date      Open      High       Low     Close  \
0 2010-06-29 00:00:00-04:00  1.266667  1.666667  1.169333  1.592667
1 2010-06-30 00:00:00-04:00  1.719333  2.028000  1.553333  1.588667
2 2010-07-01 00:00:00-04:00  1.666667  1.728000  1.351333  1.464000
3 2010-07-02 00:00:00-04:00  1.533333  1.540000  1.247333  1.280000
4 2010-07-06 00:00:00-04:00  1.333333  1.333333  1.055333  1.074000

      Volume  Dividends  Stock Splits
0  281494500        0.0           0.0
1  257806500        0.0           0.0
2  123282000        0.0           0.0
3   77097000        0.0           0.0
4  103003500        0.0           0.0

In [273]:
amazon = yf.Ticker("AMZN")
amazon_data = amazon.history(period="max")
amazon_data.reset_index(inplace=True)
print(amazon_data.head())

                       Date      Open      High       Low     Close  \
0 1997-05-15 00:00:00-04:00  0.121875  0.125000  0.096354  0.097917
1 1997-05-16 00:00:00-04:00  0.098438  0.098958  0.085417  0.086458
2 1997-05-19 00:00:00-04:00  0.088021  0.088542  0.081250  0.085417
3 1997-05-20 00:00:00-04:00  0.086458  0.087500  0.081771  0.081771
4 1997-05-21 00:00:00-04:00  0.081771  0.082292  0.068750  0.071354

       Volume  Dividends  Stock Splits
0  1443120000        0.0           0.0
1   294000000        0.0           0.0
2   122136000        0.0           0.0
3   109344000        0.0           0.0
4   377064000        0.0           0.0

In [274]:
import plotly.graph_objects as go
from plotly.subplots import make_subplots

In [275]:
def make_graph(stock_data, revenue_data, company_name):

    fig = make_subplots(
        rows=2,
        cols=1,
        subplot_titles=(f"{company_name} Stock Price",
                         f"{company_name} Revenue")
    )


    fig.add_trace(
    go.Scatter(
    x=revenue_data["Year"],
    y=revenue_data["Revenue"],
    mode="lines+markers",
    name="Revenue"
),
        row=1,
        col=1
    )

    # نمودار درآمد
    fig.add_trace(
        go.Scatter(
            x=revenue_data["Year"],
            y=revenue_data["Revenue"],
            name="Revenue"
        ),
        row=2,
        col=1
    )

    fig.update_layout(
        height=700,
        showlegend=False,
        title=company_name
    )
    import plotly.io as pio

    pio.renderers.default = "browser"
    fig.show()

In [276]:
def convert_revenue(value):


    if isinstance(value, (int, float)):
        return value

    value = value.replace(",", "").strip()

    if value.endswith("T"):
        return float(value[:-1]) * 1_000_000_000_000

    elif value.endswith("B"):
        return float(value[:-1]) * 1_000_000_000

    elif value.endswith("M"):
        return float(value[:-1]) * 1_000_000

    return float(value)

In [277]:
revenue["Revenue"] = revenue["Revenue"].apply(convert_revenue)

revenue2["Revenue"] = revenue2["Revenue"].apply(convert_revenue)

In [278]:
revenue["Year"] = revenue["Year"].astype(int)
revenue2["Year"] = revenue2["Year"].astype(int)

revenue = revenue.sort_values("Year")
revenue2 = revenue2.sort_values("Year")

In [290]:
make_graph(tesla_data, revenue, "Tesla")

In [291]:
make_graph(amazon_data, revenue2, "Amazon")

In [281]:
revenue.to_csv("data/tesla_revenue.csv", index=False)

revenue2.to_csv("data/amazon_revenue.csv", index=False)

tesla_data.to_csv("data/tesla_stock.csv", index=False)

amazon_data.to_csv("data/amazon_stock.csv", index=False)

In [282]:
revenue["Revenue Growth (%)"] = revenue["Revenue"].pct_change() * 100
revenue

    Year       Revenue  Revenue Growth (%)
17  2009  1.100000e+08                 NaN
16  2010  1.100000e+08            0.000000
15  2011  2.000000e+08           81.818182
14  2012  4.100000e+08          105.000000
13  2013  2.010000e+09          390.243902
12  2014  3.190000e+09           58.706468
11  2015  4.040000e+09           26.645768
10  2016  7.000000e+09           73.267327
9   2017  1.175000e+10           67.857143
8   2018  2.146000e+10           82.638298
7   2019  2.457000e+10           14.492078
6   2020  3.153000e+10           28.327228
5   2021  5.382000e+10           70.694577
4   2022  8.146000e+10           51.356373
3   2023  9.677000e+10           18.794500
2   2024  9.769000e+10            0.950708
1   2025  9.482000e+10           -2.937865
0   2026  9.787000e+10            3.216621

In [283]:
print(revenue["Revenue Growth (%)"].round(2))

17       NaN
16      0.00
15     81.82
14    105.00
13    390.24
12     58.71
11     26.65
10     73.27
9      67.86
8      82.64
7      14.49
6      28.33
5      70.69
4      51.36
3      18.79
2       0.95
1      -2.94
0       3.22
Name: Revenue Growth (%), dtype: float64

In [284]:
revenue2["Revenue Growth (%)"] = revenue2["Revenue"].pct_change() * 100
revenue2

    Year       Revenue  Revenue Growth (%)
30  1996  2.222000e+07                 NaN
29  1997  2.500000e+08         1025.112511
28  1998  1.150000e+09          360.000000
27  1999  3.130000e+09          172.173913
26  2000  6.230000e+09           99.041534
25  2001  7.510000e+09           20.545746
24  2002  7.510000e+09            0.000000
23  2003  8.090000e+09            7.723036
22  2004  9.690000e+09           19.777503
21  2005  1.242000e+10           28.173375
20  2006  1.520000e+10           22.383253
19  2007  1.936000e+10           27.368421
18  2008  3.302000e+10           70.557851
17  2009  3.374000e+10            2.180497
16  2010  4.433000e+10           31.387078
15  2011  6.160000e+10           38.957816
14  2012  7.426000e+10           20.551948
13  2013  9.060000e+10           22.003771
12  2014  1.135700e+11           25.353201
11  2015  1.563400e+11           37.659593
10  2016  1.963100e+11           25.566074
9   2017  2.504400e+11           27.573735
8   2018  3.471900e+11           38.632008
7   2019  4.165200e+11           19.968893
6   2020  5.350500e+11           28.457217
5   2021  6.878300e+11           28.554341
4   2022  8.095400e+11           17.694779
3   2023  9.088900e+11           12.272402
2   2024  1.131000e+12           24.437501
1   2025  1.237000e+12            9.372237
0   2026  1.269000e+12            2.586904

In [285]:
print(revenue2["Revenue Growth (%)"].round(2))

30        NaN
29    1025.11
28     360.00
27     172.17
26      99.04
25      20.55
24       0.00
23       7.72
22      19.78
21      28.17
20      22.38
19      27.37
18      70.56
17       2.18
16      31.39
15      38.96
14      20.55
13      22.00
12      25.35
11      37.66
10      25.57
9       27.57
8       38.63
7       19.97
6       28.46
5       28.55
4       17.69
3       12.27
2       24.44
1        9.37
0        2.59
Name: Revenue Growth (%), dtype: float64

In [286]:
print(revenue.describe())

              Year       Revenue  Revenue Growth (%)
count    18.000000  1.800000e+01           17.000000
mean   2017.500000  3.493389e+10           63.004195
std       5.338539  4.008731e+10           91.003615
min    2009.000000  1.100000e+08           -2.937865
25%    2013.250000  2.305000e+09           14.492078
50%    2017.500000  1.660500e+10           51.356373
75%    2021.750000  7.455000e+10           73.267327
max    2026.000000  9.787000e+10          390.243902

In [287]:
print(revenue2.describe())

              Year       Revenue  Revenue Growth (%)
count    31.000000  3.100000e+01           30.000000
mean   2011.000000  2.737675e+11           75.535571
std       9.092121  3.996886e+11          191.922766
min    1996.000000  2.222000e+07            0.000000
25%    2003.500000  8.890000e+09           19.825351
50%    2011.000000  6.160000e+10           25.459637
75%    2018.500000  3.818550e+11           36.091464
max    2026.000000  1.269000e+12         1025.112511

In [292]:
import plotly.express as px

fig = px.bar(
    revenue,
    x="Year",
    y="Revenue Growth (%)",
    title="Tesla Revenue Growth (%)"
)

fig.show()

In [293]:
import plotly.express as px

fig = px.bar(
    revenue2,
    x="Year",
    y="Revenue Growth (%)",
    title="Amazon Revenue Growth (%)"
)

fig.show()